/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Estructuras.Balance;
import Estructuras.BalanceException;
import Estructuras.ColaException;
import Estructuras.LogicCalculate;
import Estructuras.OrdinalOperators;
import Estructuras.PilaException;
import Estructuras.SpecialOperators;
import Estructuras.SustitutionLetters;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tpcalc.TPCalc;

/**
 *
 * @author Alana
 */
public class Calculate extends javax.swing.JDialog {
              

    /**
     * Creates new form Calculate
     */
    public Calculate(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.pink);
        this.setTitle("Ingrese los datos a calcular");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        screen_tf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        sum_bt = new javax.swing.JButton();
        multiplication_bt = new javax.swing.JButton();
        res_bt = new javax.swing.JButton();
        facto_bt = new javax.swing.JButton();
        sen_bt = new javax.swing.JButton();
        cos_bt = new javax.swing.JButton();
        tan_bt = new javax.swing.JButton();
        divition_bt = new javax.swing.JButton();
        sqrt_bt = new javax.swing.JButton();
        pow_bt = new javax.swing.JButton();
        calculate1_bt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        screen_tf.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        screen_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screen_tfActionPerformed(evt);
            }
        });

        sum_bt.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        sum_bt.setText("+");
        sum_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sum_btActionPerformed(evt);
            }
        });

        multiplication_bt.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        multiplication_bt.setText("*");
        multiplication_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplication_btActionPerformed(evt);
            }
        });

        res_bt.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        res_bt.setText("-");
        res_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res_btActionPerformed(evt);
            }
        });

        facto_bt.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        facto_bt.setText("Facto");
        facto_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facto_btActionPerformed(evt);
            }
        });

        sen_bt.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        sen_bt.setText("sen");
        sen_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sen_btActionPerformed(evt);
            }
        });

        cos_bt.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        cos_bt.setText("cos");
        cos_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cos_btActionPerformed(evt);
            }
        });

        tan_bt.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        tan_bt.setText("tan");
        tan_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tan_btActionPerformed(evt);
            }
        });

        divition_bt.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        divition_bt.setText("/");
        divition_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divition_btActionPerformed(evt);
            }
        });

        sqrt_bt.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        sqrt_bt.setText("SQRT");
        sqrt_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrt_btActionPerformed(evt);
            }
        });

        pow_bt.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        pow_bt.setText("^");
        pow_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pow_btActionPerformed(evt);
            }
        });

        calculate1_bt.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        calculate1_bt.setText("Calcular");
        calculate1_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate1_btActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/WhatsApp Image 2020-06-24 at 3.56.06 PM.jpeg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(screen_tf, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sum_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(res_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sen_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tan_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calculate1_bt)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pow_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cos_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(divition_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sqrt_bt))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(facto_bt))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(multiplication_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(screen_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(divition_bt)
                    .addComponent(res_bt)
                    .addComponent(sum_bt)
                    .addComponent(pow_bt)
                    .addComponent(multiplication_bt))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tan_bt)
                    .addComponent(sen_bt)
                    .addComponent(sqrt_bt)
                    .addComponent(cos_bt)
                    .addComponent(facto_bt))
                .addGap(57, 57, 57)
                .addComponent(calculate1_bt)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void screen_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screen_tfActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_screen_tfActionPerformed

    private void sum_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sum_btActionPerformed
        // TODO add your handling code here:
        this.screen_tf.setText(this.screen_tf.getText() + OrdinalOperators.SUM.getSymbol());
    }//GEN-LAST:event_sum_btActionPerformed

    private void res_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res_btActionPerformed
        // TODO add your handling code here:
         this.screen_tf.setText(this.screen_tf.getText() + OrdinalOperators.RES.getSymbol());
    }//GEN-LAST:event_res_btActionPerformed

    private void pow_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pow_btActionPerformed
        // TODO add your handling code here:
         this.screen_tf.setText(this.screen_tf.getText() + OrdinalOperators.POWER.getSymbol());
    }//GEN-LAST:event_pow_btActionPerformed

    private void divition_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divition_btActionPerformed
        // TODO add your handling code here:
         this.screen_tf.setText(this.screen_tf.getText() + OrdinalOperators.DIVISION.getSymbol());
    }//GEN-LAST:event_divition_btActionPerformed

    private void multiplication_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplication_btActionPerformed
        // TODO add your handling code here:
         this.screen_tf.setText(this.screen_tf.getText() + OrdinalOperators.MULTIPLICATION.getSymbol());
    }//GEN-LAST:event_multiplication_btActionPerformed

    private void sen_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sen_btActionPerformed
        // TODO add your handling code here:
         this.screen_tf.setText(this.screen_tf.getText() + SpecialOperators.SEN.getDescription());
    }//GEN-LAST:event_sen_btActionPerformed

    private void tan_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tan_btActionPerformed
        // TODO add your handling code here:
          this.screen_tf.setText(this.screen_tf.getText() + SpecialOperators.TAN.getDescription());
    }//GEN-LAST:event_tan_btActionPerformed

    private void cos_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cos_btActionPerformed
        // TODO add your handling code here:
          this.screen_tf.setText(this.screen_tf.getText() + SpecialOperators.COS.getDescription());
    }//GEN-LAST:event_cos_btActionPerformed

    private void sqrt_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrt_btActionPerformed
        // TODO add your handling code here:
          this.screen_tf.setText(this.screen_tf.getText() + SpecialOperators.SQRT.getDescription());
    }//GEN-LAST:event_sqrt_btActionPerformed

    private void facto_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facto_btActionPerformed
        // TODO add your handling code here:
          this.screen_tf.setText(this.screen_tf.getText() + SpecialOperators.FACTO.getDescription());
    }//GEN-LAST:event_facto_btActionPerformed

    private void calculate1_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculate1_btActionPerformed
        // TODO add your handling code here:
          try {
            Balance balance = new Balance();
            balance.split(this.screen_tf.getText());
            balance.formulaPosfija();
            SustitutionLetters sustitution = new SustitutionLetters(balance.getColaFormulaPostfija());

           while(sustitution.cantLetters() != 0) {
                String letter = sustitution.letters();
                double data = Double.parseDouble(JOptionPane.showInputDialog("Ingrese el valor de la variable " + letter + ":"));
                sustitution.gg(letter, data);
            }
            LogicCalculate calculate = new LogicCalculate(sustitution.getFormulaPostfija());
            this.screen_tf.setText(String.valueOf(calculate.calculate()));
            this.screen_tf.setEditable(false);
            this.calculate1_bt.setEnabled(false);


        } catch (ColaException | BalanceException  | PilaException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } 
    }//GEN-LAST:event_calculate1_btActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Calculate dialog = new Calculate(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculate1_bt;
    private javax.swing.JButton cos_bt;
    private javax.swing.JButton divition_bt;
    private javax.swing.JButton facto_bt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton multiplication_bt;
    private javax.swing.JButton pow_bt;
    private javax.swing.JButton res_bt;
    private javax.swing.JTextField screen_tf;
    private javax.swing.JButton sen_bt;
    private javax.swing.JButton sqrt_bt;
    private javax.swing.JButton sum_bt;
    private javax.swing.JButton tan_bt;
    // End of variables declaration//GEN-END:variables
}
